apiVersion: v1
kind: Service
metadata:
  name: my-emp
  labels:
    run: my-emp
spec:
  ports:
    - port: 80 # puerto interno de la LAN
      targetPort: 3000 # exponiendo en el exterior
      protocol: TCP
  type: NodePort # salida a internet
  selector:
    run: my-emp

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-emp
spec:
  replicas: 3
  template:
    metadata:
      labels:
        run: my-emp
    spec:
      containers:
        - name: my-emp
          image: isaaccarrada/my-emp
          ports:
            - containerPort: 3000
